[package]
name = "rustup-toolchain-install-master"
version = "1.12.1"
authors = ["kennytm <kennytm@gmail.com>"]
categories = ["development-tools"]
edition = "2024"
keywords = ["rustup"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/kennytm/rustup-toolchain-install-master"
description = "Install master rustc toolchain into rustup"
rust-version = "1.97.1"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
colored = "3"
anyhow = "1.0.100"
home = "0.5"
indicatif = "0.18"
reqwest = { version = "0.13", features = ["blocking", "gzip"]}
clap = { version = "4.5", features = ["derive", "cargo"] }
tar = "0.4"
tempfile = "3"
xz2 = "0.1"
